---

# Update the Packages to the latest
#******************************************************************************
- name: Update all packages
  package:
    name: "*"
    state: latest
  when: ansible_distribution != "Ubuntu"

- name: Update Ubuntu
  apt:
    upgrade: dist
  when: ansible_distribution == "Ubuntu"

- name: SELinux - Set SELinux to enforcing mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'

# include task files
- include_tasks: auditd.yml
- include_tasks: cron.yml
- include_tasks: limits.yml
- include_tasks: login_defs.yml
- include_tasks: pam_passwd.yml
- include_tasks: sudoer.yml
- include_tasks: sshd_config.yml
- include_tasks: sysctl.yml